spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/surveydb?useUnicode=true&characterEncdoing=UTF-8&serverTimezone=UTC
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create
      $ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    rest:
      base-path: /
      default-page-size: 10
      max-page-size: 10